[package]
name = "depgraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.53"
futures = "0.3.21"
once_cell = "1.9.0"
serde_json = { version = "1.0.79", features = ["std"] }
swc = "0.127.4"
swc_common = "0.17.5"
swc_ecma_dep_graph = "0.59.0"
swc_ecma_parser = "0.88.3"
tokio = { version = "1", features = ["fs", "rt-multi-thread", "sync", "macros", "io-std", "io-util"] }
