/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Dependency {
  kind: number
  name: string
  line: number
  column: number
  exports?: Array<[string, string]>
}
export function analyze(fileName: string, source?: string | undefined | null): Promise<Array<Dependency>>
