/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Dependency {
  kind: number
  name: string
  line: number
  column: number
  exports?: Array<string>
}
export function analyze(fileName: string, source: string): Promise<Array<Dependency>>
