name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: tag version
        required: true
        type: string

jobs:
  build:
    uses: './.github/workflows/rust.yml'
    with:
      version: ${{ github.event.inputs.version }}

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: restructure asset
        run: |
          for target in x86_64-unknown-linux-gnu x86_64-apple-darwin aarch64-apple-darwin; do
            mv artifacts/depgraph-${target}/depgraph depgraph-${target}
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          files: |
            depgraph-x86_64-unknown-linux-gnu
            depgraph-x86_64-apple-darwin
            depgraph-aarch64-apple-darwin

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: touch depgraph
      - run: npm ci
      - run: rm depgraph
      - run: npm version --no-git-tag-version -f ${{ github.event.inputs.version }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
